export const candidates = [
  {
    id: 1,
    name: "John Smith",
    age: "25",
    experience:
      "2 years as Software Engineer at Google, focused on full-stack web development.",
    academic: "Bachelor's in Computer Science",
    major: "Software Engineering",
    matching_score: 0.90,
    email: "john.smith@example.com",
    skills: "Java, Python, React, Node.js",
    certification: "AWS Certified Solutions Architect",
    personality: "Analytical, Detail-oriented",
    language: "English (Native), Spanish (Intermediate)",
  },
  {
    id: 2,
    name: "Emily Johnson",
    age: "23",
    experience:
      "1.5 years as IT Support at Microsoft, handling technical troubleshooting and network issues.",
    academic: "Bachelor's in Information Technology",
    major: "Network Engineering",
    matching_score: 0.85,
    email: "emily.johnson@example.com",
    skills: "SQL, Linux, Networking",
    certification: "CCNA, ITIL Foundation",
    personality: "Problem-solver, Collaborative",
    language: "English (Native), French (Basic)",
  },
  {
    id: 3,
    name: "Michael Brown",
    age: "27",
    experience:
      "3 years as Cloud Engineer at Amazon Web Services (AWS), specializing in cloud infrastructure and automation.",
    academic: "Bachelor's in Information Technology",
    major: "Cloud Computing",
    matching_score: 0.82,
    email: "michael.brown@example.com",
    skills: "AWS, Azure, Docker, Kubernetes",
    certification: "Azure Administrator, AWS Certified Developer",
    personality: "Team-player, Adaptable",
    language: "English (Native)",
  },
  {
    id: 4,
    name: "Sarah Davis",
    age: "24",
    experience:
      "2 years as Software QA Tester at Facebook, working on automated testing for mobile apps.",
    academic: "Bachelor's in Computer Science",
    major: "Software Testing",
    matching_score: 0.80,
    email: "sarah.davis@example.com",
    skills: "Selenium, JIRA, Manual Testing",
    certification: "ISTQB Certified Tester",
    personality: "Detail-oriented, Organized",
    language: "English (Native)",
  },
  {
    id: 5,
    name: "David Martinez",
    age: "26",
    experience:
      "3 years as Front-End Developer at Shopify, building responsive e-commerce websites.",
    academic: "Bachelor's in Computer Science",
    major: "Web Development",
    matching_score: 0.78,
    email: "david.martinez@example.com",
    skills: "HTML, CSS, JavaScript, PHP, React",
    certification: "Google Mobile Web Specialist",
    personality: "Creative, Self-motivated",
    language: "English (Fluent), Spanish (Native)",
  },
  {
    id: 6,
    name: "Anna Lee",
    age: "22",
    experience:
      "1 year as Data Analyst Intern at IBM, focusing on data visualization and insights.",
    academic: "Bachelor's in Data Science",
    major: "Data Analytics",
    matching_score: 0.76,
    email: "anna.lee@example.com",
    skills: "Python, R, SQL, Excel",
    certification: "Google Data Analytics",
    personality: "Analytical, Problem-solver",
    language: "English (Native), Korean (Intermediate)",
  },
  {
    id: 7,
    name: "James Wilson",
    age: "28",
    experience:
      "4 years as DevOps Engineer at Netflix, managing CI/CD pipelines and cloud automation.",
    academic: "Master's in Computer Science",
    major: "DevOps",
    matching_score: 0.74,
    email: "james.wilson@example.com",
    skills: "AWS, Docker, Kubernetes, Jenkins",
    certification: "AWS Certified DevOps Engineer",
    personality: "Detail-oriented, Adaptable",
    language: "English (Native)",
  },
  {
    id: 8,
    name: "Olivia Martinez",
    age: "24",
    experience:
      "2 years as Database Administrator at Oracle, working with SQL and NoSQL databases.",
    academic: "Bachelor's in Information Systems",
    major: "Database Management",
    matching_score: 0.72,
    email: "olivia.martinez@example.com",
    skills: "SQL, Oracle, MySQL, MongoDB",
    certification: "Oracle Certified Professional",
    personality: "Organized, Methodical",
    language: "English (Fluent), Spanish (Native)",
  },
  {
    id: 9,
    name: "Christopher Anderson",
    age: "23",
    experience:
      "1 year as IT Support Specialist at Dell, providing technical assistance for software and hardware issues.",
    academic: "Bachelor's in Information Technology",
    major: "IT Support",
    matching_score: 0.70,
    email: "christopher.anderson@example.com",
    skills: "Windows, Linux, Networking",
    certification: "CompTIA A+, Microsoft Certified: Azure Fundamentals",
    personality: "Patient, Problem-solver",
    language: "English (Native)",
  },
  {
    id: 10,
    name: "Sophia Hernandez",
    age: "25",
    experience:
      "3 years as Cybersecurity Analyst at Cisco, focusing on network security and penetration testing.",
    academic: "Bachelor's in Cybersecurity",
    major: "Cybersecurity",
    matching_score: 0.68,
    email: "sophia.hernandez@example.com",
    skills: "Penetration Testing, Firewalls, SIEM",
    certification: "Certified Ethical Hacker (CEH), CISSP",
    personality: "Cautious, Detail-oriented",
    language: "English (Fluent), Spanish (Native)",
  },
  {
    id: 11,
    name: "Liam White",
    age: "21",
    experience:
      "1 year as Junior Front-End Developer at Twitter, working on React-based web apps.",
    academic: "Bachelor's in Computer Science",
    major: "Front-End Development",
    matching_score: 0.65,
    email: "liam.white@example.com",
    skills: "HTML, CSS, JavaScript, React",
    certification: "Front-End Developer Certification",
    personality: "Creative, Team-player",
    language: "English (Native)",
  },
  {
    id: 12,
    name: "Isabella Clark",
    age: "26",
    experience:
      "3 years as Mobile App Developer at Uber, developing iOS and Android apps.",
    academic: "Bachelor's in Computer Science",
    major: "Mobile App Development",
    matching_score: 0.62,
    email: "isabella.clark@example.com",
    skills: "Swift, Kotlin, Flutter, React Native",
    certification: "Google Associate Android Developer",
    personality: "Innovative, Self-motivated",
    language: "English (Native)",
  },
  {
    id: 13,
    name: "Ethan Scott",
    age: "29",
    experience:
      "5 years as IT Project Manager at Accenture, leading software development projects.",
    academic: "Master's in Information Technology",
    major: "Project Management",
    matching_score: 0.60,
    email: "ethan.scott@example.com",
    skills: "Agile, Scrum, JIRA, Microsoft Project",
    certification: "PMP, Scrum Master",
    personality: "Organized, Leader",
    language: "English (Native)",
  },
  {
    id: 14,
    name: "Ava Lewis",
    age: "22",
    experience:
      "6 months as Software Tester Intern at Dropbox, focusing on manual and automated testing.",
    academic: "Bachelor's in Computer Science",
    major: "Software Testing",
    matching_score: 0.55,
    email: "ava.lewis@example.com",
    skills: "Selenium, JIRA, TestRail",
    certification: "ISTQB Certified Tester",
    personality: "Meticulous, Collaborative",
    language: "English (Native)",
  },
  {
    id: 15,
    name: "William Adams",
    age: "24",
    experience:
      "1 year as System Administrator at IBM, managing Linux and Windows server environments.",
    academic: "Bachelor's in Information Technology",
    major: "System Administration",
    matching_score: 0.40,
    email: "william.adams@example.com",
    skills: "Linux, Windows Server, VMware",
    certification: "Microsoft Certified Systems Administrator",
    personality: "Detail-oriented, Problem-solver",
    language: "English (Native)",
  },
];
