export const questions = [
  { id: 1, type: "Q1", question: "You often make new friends." },
  { id: 2, type: "Q2", question: "You prefer to plan things in advance." },
  { id: 3, type: "Q3", question: "You feel comfortable in social situations." },
  { id: 4, type: "Q4", question: "You often seek out new experiences." },
  {
    id: 5,
    type: "Q5",
    question: "You prefer working in a team rather than alone.",
  },
  { id: 6, type: "Q6", question: "You often help others without being asked." },
  { id: 7, type: "Q7", question: "You like to express your opinions openly." },
  { id: 8, type: "Q8", question: "You enjoy taking risks." },
  {
    id: 9,
    type: "Q9",
    question: "You often feel anxious in unfamiliar situations.",
  },
  {
    id: 10,
    type: "Q10",
    question: "You value tradition and established practices.",
  },
  { id: 11, type: "Q11", question: "You are detail-oriented." },
  { id: 12, type: "Q12", question: "You tend to think before you speak." },
  { id: 13, type: "Q13", question: "You enjoy exploring new ideas." },
  { id: 14, type: "Q14", question: "You prefer routine over spontaneity." },
  {
    id: 15,
    type: "Q15",
    question: "You often feel empathetic towards others.",
  },
  {
    id: 16,
    type: "Q16",
    question: "You are more of a listener than a talker.",
  },
  { id: 17, type: "Q17", question: "You like to solve problems logically." },
  {
    id: 18,
    type: "Q18",
    question: "You often take the lead in group projects.",
  },
  {
    id: 19,
    type: "Q19",
    question: "You feel comfortable sharing personal feelings.",
  },
  { id: 20, type: "Q20", question: "You enjoy meeting new people." },
  { id: 21, type: "Q21", question: "You often think outside the box." },
  { id: 22, type: "Q22", question: "You feel overwhelmed by large groups." },
  { id: 23, type: "Q23", question: "You often seek feedback from others." },
  {
    id: 24,
    type: "Q24",
    question: "You like to help others achieve their goals.",
  },
  { id: 25, type: "Q25", question: "You prefer to keep your options open." },
  { id: 26, type: "Q26", question: "You enjoy working on creative projects." },
  { id: 27, type: "Q27", question: "You often feel stressed by deadlines." },
  { id: 28, type: "Q28", question: "You find it easy to adapt to change." },
  { id: 29, type: "Q29", question: "You enjoy planning events." },
  { id: 30, type: "Q30", question: "You often reflect on your feelings." },
  { id: 31, type: "Q31", question: "You prefer detailed instructions." },
  {
    id: 32,
    type: "Q32",
    question: "You like to support your friends emotionally.",
  },
  {
    id: 33,
    type: "Q33",
    question: "You often try to understand different perspectives.",
  },
  { id: 34, type: "Q34", question: "You value honesty in relationships." },
  { id: 35, type: "Q35", question: "You find it easy to make decisions." },
  {
    id: 36,
    type: "Q36",
    question: "You often feel nervous before public speaking.",
  },
  { id: 37, type: "Q37", question: "You enjoy working independently." },
  { id: 38, type: "Q38", question: "You like to set long-term goals." },
  { id: 39, type: "Q39", question: "You feel comfortable confronting issues." },
  {
    id: 40,
    type: "Q40",
    question: "You often take time to relax and recharge.",
  },
  { id: 41, type: "Q41", question: "You find joy in helping others." },
  { id: 42, type: "Q42", question: "You often seek harmony in relationships." },
  {
    id: 43,
    type: "Q43",
    question: "You prefer to stick to familiar routines.",
  },
  { id: 44, type: "Q44", question: "You enjoy being the center of attention." },
  { id: 45, type: "Q45", question: "You often challenge the status quo." },
  {
    id: 46,
    type: "Q46",
    question: "You feel comfortable giving presentations.",
  },
  { id: 47, type: "Q47", question: "You like to encourage others." },
  {
    id: 48,
    type: "Q48",
    question: "You often find it easy to forgive others.",
  },
  { id: 49, type: "Q49", question: "You enjoy learning new things." },
  {
    id: 50,
    type: "Q50",
    question: "You often seek to understand your own emotions.",
  },
];
