export const questions = [
  { id: 1, code: "Q1", question: "You often make new friends." },
  { id: 2, code: "Q2", question: "You prefer to plan things in advance." },
  { id: 3, code: "Q3", question: "You feel comfortable in social situations." },
  { id: 4, code: "Q4", question: "You often seek out new experiences." },
  {
    id: 5,
    code: "Q5",
    question: "You prefer working in a team rather than alone.",
  },
  { id: 6, code: "Q6", question: "You often help others without being asked." },
  { id: 7, code: "Q7", question: "You like to express your opinions openly." },
  { id: 8, code: "Q8", question: "You enjoy taking risks." },
  {
    id: 9,
    code: "Q9",
    question: "You often feel anxious in unfamiliar situations.",
  },
  {
    id: 10,
    code: "Q10",
    question: "You value tradition and established practices.",
  },
  { id: 11, code: "Q11", question: "You are detail-oriented." },
  { id: 12, code: "Q12", question: "You tend to think before you speak." },
  { id: 13, code: "Q13", question: "You enjoy exploring new ideas." },
  { id: 14, code: "Q14", question: "You prefer routine over spontaneity." },
  {
    id: 15,
    code: "Q15",
    question: "You often feel empathetic towards others.",
  },
  {
    id: 16,
    code: "Q16",
    question: "You are more of a listener than a talker.",
  },
  { id: 17, code: "Q17", question: "You like to solve problems logically." },
  {
    id: 18,
    code: "Q18",
    question: "You often take the lead in group projects.",
  },
  {
    id: 19,
    code: "Q19",
    question: "You feel comfortable sharing personal feelings.",
  },
  { id: 20, code: "Q20", question: "You enjoy meeting new people." },
  { id: 21, code: "Q21", question: "You often think outside the box." },
  { id: 22, code: "Q22", question: "You feel overwhelmed by large groups." },
  { id: 23, code: "Q23", question: "You often seek feedback from others." },
  {
    id: 24,
    code: "Q24",
    question: "You like to help others achieve their goals.",
  },
  { id: 25, code: "Q25", question: "You prefer to keep your options open." },
  { id: 26, code: "Q26", question: "You enjoy working on creative projects." },
  { id: 27, code: "Q27", question: "You often feel stressed by deadlines." },
  { id: 28, code: "Q28", question: "You find it easy to adapt to change." },
  { id: 29, code: "Q29", question: "You enjoy planning events." },
  { id: 30, code: "Q30", question: "You often reflect on your feelings." },
  { id: 31, code: "Q31", question: "You prefer detailed instructions." },
  {
    id: 32,
    code: "Q32",
    question: "You like to support your friends emotionally.",
  },
  {
    id: 33,
    code: "Q33",
    question: "You often try to understand different perspectives.",
  },
  { id: 34, code: "Q34", question: "You value honesty in relationships." },
  { id: 35, code: "Q35", question: "You find it easy to make decisions." },
  {
    id: 36,
    code: "Q36",
    question: "You often feel nervous before public speaking.",
  },
  { id: 37, code: "Q37", question: "You enjoy working independently." },
  { id: 38, code: "Q38", question: "You like to set long-term goals." },
  { id: 39, code: "Q39", question: "You feel comfortable confronting issues." },
  {
    id: 40,
    code: "Q40",
    question: "You often take time to relax and recharge.",
  },
  { id: 41, code: "Q41", question: "You find joy in helping others." },
  { id: 42, code: "Q42", question: "You often seek harmony in relationships." },
  {
    id: 43,
    code: "Q43",
    question: "You prefer to stick to familiar routines.",
  },
  { id: 44, code: "Q44", question: "You enjoy being the center of attention." },
  { id: 45, code: "Q45", question: "You often challenge the status quo." },
  {
    id: 46,
    code: "Q46",
    question: "You feel comfortable giving presentations.",
  },
  { id: 47, code: "Q47", question: "You like to encourage others." },
  {
    id: 48,
    code: "Q48",
    question: "You often find it easy to forgive others.",
  },
  { id: 49, code: "Q49", question: "You enjoy learning new things." },
  {
    id: 50,
    code: "Q50",
    question: "You often seek to understand your own emotions.",
  },
];
